authors = ["Petr Vana <petvana@centrum.cz>"]
name = "ExampleWithPlots"
uuid = "869e8dd4-39bf-4a4d-8b19-a1d744f04ecb"
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[extras]
AutoSysimages = "4eb35182-e5c8-446d-8ecc-33e714a26cef"
